"use client";

import { useEffect, useState } from "react";
import { Button } from "../ui/Button";
import { generateOwnerSecret } from "../../lib/zk";

/**
 * Issues a fresh 256-bit owner secret and forces the user to acknowledge
 * saving it. Secrets are generated by the browser CSPRNG rather than typed,
 * because a human-chosen passphrase would be recoverable from the public
 * commitment by offline dictionary search.
 */
export function OwnerSecretField({
  value,
  onChange,
  label = "Your Owner Secret (256-bit — save it now!)"
}: {
  value: string;
  onChange: (secret: string) => void;
  label?: string;
}) {
  const [acknowledged, setAcknowledged] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!value) onChange(generateOwnerSecret());
  }, [value, onChange]);

  async function copy() {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      setCopied(false);
    }
  }

  function download() {
    const blob = new Blob(
      [
        "LandChain owner secret\n",
        "======================\n\n",
        `${value}\n\n`,
        "This is the ONLY credential that proves you own this land.\n",
        "It is not stored on any server and cannot be recovered if lost.\n",
        "Keep it offline and private.\n"
      ],
      { type: "text/plain" }
    );
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = "landchain-owner-secret.txt";
    anchor.click();
    setTimeout(() => URL.revokeObjectURL(url), 30000);
  }

  return (
    <div className="grid gap-2">
      <label className="text-sm font-medium text-[#34433b]">{label}</label>
      <p className="break-all rounded-md border border-[#c6d0c9] bg-[#f0f4f0] px-3 py-2 font-mono text-xs text-[#17201b]">
        {value || "generating…"}
      </p>
      <div className="flex flex-wrap gap-2">
        <Button onClick={copy} type="button" variant="secondary">
          {copied ? "Copied!" : "Copy"}
        </Button>
        <Button onClick={download} type="button" variant="secondary">
          Download
        </Button>
        <Button onClick={() => onChange(generateOwnerSecret())} type="button" variant="secondary">
          Regenerate
        </Button>
      </div>
      <p className="text-xs text-[#65766b]">
        Generated in your browser with 256 bits of entropy. It never reaches our servers, and it cannot be reset or
        recovered — if you lose it you permanently lose the ability to prove ownership.
      </p>
      <label className="flex items-start gap-2 text-sm text-[#34433b]">
        <input
          checked={acknowledged}
          className="mt-1"
          name="secretSaved"
          onChange={(event) => setAcknowledged(event.target.checked)}
          required
          type="checkbox"
        />
        I have saved this secret somewhere safe.
      </label>
    </div>
  );
}
